// Do not edit: this file is generated by `ghat generate`.
declare global {
  /**
   * Download a build artifact that was previously uploaded in the workflow by the upload-artifact action
   * @see https://github.com/actions/download-artifact
   */
  function uses(
    action: "actions/download-artifact",
    options?: UsesOptions<{
    /** Name of the artifact to download. If unspecified, all artifacts for the run are downloaded. */
    name?: string;
    /** IDs of the artifacts to download, comma-separated. Either inputs `artifact-ids` or `name` can be used, but not both. */
    artifact_ids?: string;
    /** Destination path. Supports basic tilde expansion. Defaults to $GITHUB_WORKSPACE */
    path?: string;
    /** A glob pattern matching the artifacts that should be downloaded. Ignored if name is specified. */
    pattern?: string;
    /** When multiple artifacts are matched, this changes the behavior of the destination directories. If true, the downloaded artifacts will be in the same directory specified by path. If false, the downloaded artifacts will be extracted into individual named directories within the specified path. */
    merge_multiple?: string;
    /** The GitHub token used to authenticate with the GitHub API. This is required when downloading artifacts from a different repository or from a different workflow run. If this is not specified, the action will attempt to download artifacts from the current repository and the current workflow run. */
    github_token?: string;
    /** The repository owner and the repository name joined together by "/". If github-token is specified, this is the repository that artifacts will be downloaded from. */
    repository?: string;
    /** The id of the workflow run where the desired download artifact was uploaded from. If github-token is specified, this is the run that artifacts will be downloaded from. */
    run_id?: string;
    /** If true, the downloaded artifact will not be automatically extracted/decompressed. This is useful when you want to handle the artifact as-is without extraction. */
    skip_decompress?: string;
    /** The behavior when a downloaded artifact's digest does not match the expected digest. Options: ignore, info, warn, error. Default is error which will fail the action. */
    digest_mismatch?: string;
    }>,
  ): StepRef<{
    /** Path of artifact download */
    download_path: string;
  }>;
}
export {};
