// Do not edit: this file is generated by `ghat generate`.
declare global {
  /**
   * Cache artifacts like dependencies and build outputs to improve workflow execution time
   * @see https://github.com/actions/cache
   */
  function uses(
    action: "actions/cache",
    options: UsesOptionsRequired<{
    /** A list of files, directories, and wildcard patterns to cache and restore */
    path: string;
    /** An explicit key for restoring and saving the cache */
    key: string;
    /** An ordered multiline string listing the prefix-matched keys, that are used for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case. */
    restore_keys?: string;
    /** The chunk size used to split up large files during upload, in bytes */
    upload_chunk_size?: string;
    /** An optional boolean when enabled, allows windows runners to save or restore caches that can be restored or saved respectively on other platforms */
    enableCrossOsArchive?: string;
    /** Fail the workflow if cache entry is not found */
    fail_on_cache_miss?: string;
    /** Check if a cache entry exists for the given input(s) (key, restore-keys) without downloading the cache */
    lookup_only?: string;
    /**
     * Run the post step to save the cache even if another step before fails
     * @deprecated save-always does not work as intended and will be removed in a future release.
A separate `actions/cache/restore` step should be used instead.
See https://github.com/actions/cache/tree/main/save#always-save-cache for more details.
     */
    save_always?: string;
    }>,
  ): StepRef<{
    /** A boolean value to indicate an exact match was found for the primary key */
    cache_hit: string;
  }>;
}
export {};
