// Do not edit: this file is generated by `ghat generate`.
globalThis.__GHAT_ACTION_MAPPINGS = {
  "Swatinem/rust-cache": {
    inputs: {
      "prefix_key": "prefix-key",
      "shared_key": "shared-key",
      "add_job_id_key": "add-job-id-key",
      "add_rust_environment_hash_key": "add-rust-environment-hash-key",
      "env_vars": "env-vars",
      "cache_directories": "cache-directories",
      "cache_targets": "cache-targets",
      "cache_on_failure": "cache-on-failure",
      "cache_all_crates": "cache-all-crates",
      "cache_workspace_crates": "cache-workspace-crates",
      "save_if": "save-if",
      "cache_provider": "cache-provider",
      "cache_bin": "cache-bin",
      "lookup_only": "lookup-only"
    },
    outputs: {
      "cache_hit": "cache-hit"
    },
  },
  "actions/cache": {
    inputs: {
      "restore_keys": "restore-keys",
      "upload_chunk_size": "upload-chunk-size",
      "fail_on_cache_miss": "fail-on-cache-miss",
      "lookup_only": "lookup-only",
      "save_always": "save-always"
    },
    outputs: {
      "cache_hit": "cache-hit"
    },
  },
  "actions/checkout": {
    inputs: {
      "ssh_key": "ssh-key",
      "ssh_known_hosts": "ssh-known-hosts",
      "ssh_strict": "ssh-strict",
      "ssh_user": "ssh-user",
      "persist_credentials": "persist-credentials",
      "sparse_checkout": "sparse-checkout",
      "sparse_checkout_cone_mode": "sparse-checkout-cone-mode",
      "fetch_depth": "fetch-depth",
      "fetch_tags": "fetch-tags",
      "show_progress": "show-progress",
      "set_safe_directory": "set-safe-directory",
      "github_server_url": "github-server-url"
    },
  },
  "actions/download-artifact": {
    inputs: {
      "artifact_ids": "artifact-ids",
      "merge_multiple": "merge-multiple",
      "github_token": "github-token",
      "run_id": "run-id",
      "skip_decompress": "skip-decompress",
      "digest_mismatch": "digest-mismatch"
    },
    outputs: {
      "download_path": "download-path"
    },
  },
  "actions/setup-go": {
    inputs: {
      "go_version": "go-version",
      "go_version_file": "go-version-file",
      "check_latest": "check-latest",
      "cache_dependency_path": "cache-dependency-path"
    },
    outputs: {
      "go_version": "go-version",
      "cache_hit": "cache-hit"
    },
  },
  "actions/upload-artifact": {
    inputs: {
      "if_no_files_found": "if-no-files-found",
      "retention_days": "retention-days",
      "compression_level": "compression-level",
      "include_hidden_files": "include-hidden-files"
    },
    outputs: {
      "artifact_id": "artifact-id",
      "artifact_url": "artifact-url",
      "artifact_digest": "artifact-digest"
    },
  },
};
