use std::collections::{BTreeMap, HashMap};
use std::fmt;
use std::path::{Path, PathBuf};
use std::process::Command;

/// A test project in an isolated temp directory.
pub struct TestProject {
    dir: tempfile::TempDir,
}

/// Builder for setting up a test project.
pub struct TestProjectBuilder {
    files: HashMap<String, String>,
    init: bool,
}

/// Files generated by `ghat init` whose content is static and not worth
/// snapshotting verbatim. Shown as `[N bytes]` instead.
const REDACTED_PATHS: &[&str] = &[
    ".github/ghat/types/api.d.ts",
    ".github/ghat/tsconfig.json",
    ".github/workflows/ghat_check.yaml",
];

/// A snapshot of a project's file tree.
pub struct ProjectSnapshot {
    /// Sorted list of (relative_path, content) pairs.
    files: Vec<(String, String)>,
}

impl fmt::Display for ProjectSnapshot {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        for (path, content) in &self.files {
            if REDACTED_PATHS.contains(&path.as_str()) {
                writeln!(f, "--- {path} ---\n[{} bytes]", content.len())?;
            } else {
                write!(f, "--- {path} ---\n{content}")?;
                if !content.ends_with('\n') {
                    writeln!(f)?;
                }
            }
        }
        Ok(())
    }
}

impl ProjectSnapshot {
    /// Compute a unified diff between this snapshot and another.
    pub fn diff(&self, other: &ProjectSnapshot) -> String {
        let before: BTreeMap<&str, &str> = self
            .files
            .iter()
            .map(|(p, c)| (p.as_str(), c.as_str()))
            .collect();
        let after: BTreeMap<&str, &str> = other
            .files
            .iter()
            .map(|(p, c)| (p.as_str(), c.as_str()))
            .collect();

        let mut all_paths: BTreeMap<&str, ()> = BTreeMap::new();
        for key in before.keys().chain(after.keys()) {
            all_paths.insert(key, ());
        }

        let mut out = String::new();
        for path in all_paths.keys() {
            let old = before.get(path).copied().unwrap_or("");
            let new = after.get(path).copied().unwrap_or("");
            if old == new {
                continue;
            }

            let text_diff = similar::TextDiff::from_lines(old, new);
            let unified = text_diff
                .unified_diff()
                .context_radius(3)
                .header(&format!("a/{path}"), &format!("b/{path}"))
                .to_string();
            out.push_str(&unified);
        }
        out
    }
}

impl TestProject {
    /// Start building a new test project.
    pub fn new() -> TestProjectBuilder {
        TestProjectBuilder {
            files: HashMap::new(),
            init: false,
        }
    }

    /// Path to the temp directory root.
    pub fn path(&self) -> &Path {
        self.dir.path()
    }

    /// Read a file relative to the project root.
    pub fn read_file(&self, path: &str) -> String {
        std::fs::read_to_string(self.dir.path().join(path))
            .unwrap_or_else(|e| panic!("failed to read {path}: {e}"))
    }

    /// Check if a file exists relative to the project root.
    pub fn file_exists(&self, path: &str) -> bool {
        self.dir.path().join(path).exists()
    }

    /// Create a `CommandRunner` for running ghat with given args.
    pub fn ghat(&self, args: &[&str]) -> CommandRunner {
        CommandRunner {
            project_dir: self.dir.path().to_path_buf(),
            args: args.iter().map(|s| s.to_string()).collect(),
            envs: HashMap::new(),
        }
    }

    /// Snapshot all files in the project, sorted alphabetically by relative path.
    pub fn snapshot_full(&self) -> ProjectSnapshot {
        ProjectSnapshot {
            files: collect_all_files(self.dir.path()),
        }
    }

    /// Snapshot a generate run: command output, workflow input `.ts` files
    /// (`.github/ghat/workflows/**/*.ts`), and generated outputs
    /// (`.github/workflows/**/*`) combined into a single string.
    pub fn generate_snapshot(&self, output: &CommandOutput) -> String {
        let mut result = output.to_string();
        let files = self.snapshot_globs(&[
            ".github/ghat/workflows/**/*.ts",
            ".github/workflows/**/*",
        ]);
        result.push_str(&files.to_string());
        result
    }

    /// Snapshot files matching multiple glob patterns (relative to project root).
    pub fn snapshot_globs(&self, patterns: &[&str]) -> ProjectSnapshot {
        let mut files = BTreeMap::new();
        for pattern in patterns {
            let full_pattern = format!("{}/{pattern}", self.dir.path().display());
            for entry in glob::glob(&full_pattern).expect("invalid glob pattern") {
                let path = entry.expect("glob error");
                if path.is_file() {
                    let rel = normalize_path(
                        &path
                            .strip_prefix(self.dir.path())
                            .unwrap()
                            .to_string_lossy(),
                    );
                    let content = read_file_or_binary(&path);
                    files.insert(rel, content);
                }
            }
        }
        ProjectSnapshot {
            files: files.into_iter().collect(),
        }
    }

    /// Snapshot files matching a glob pattern (relative to project root).
    pub fn snapshot_glob(&self, pattern: &str) -> ProjectSnapshot {
        let full_pattern = format!("{}/{pattern}", self.dir.path().display());
        let mut files = BTreeMap::new();
        for entry in glob::glob(&full_pattern).expect("invalid glob pattern") {
            let path = entry.expect("glob error");
            if path.is_file() {
                let rel = normalize_path(
                    &path
                        .strip_prefix(self.dir.path())
                        .unwrap()
                        .to_string_lossy(),
                );
                let content = read_file_or_binary(&path);
                files.insert(rel, content);
            }
        }
        ProjectSnapshot {
            files: files.into_iter().collect(),
        }
    }
}

/// Collect all files under `root` into a sorted vec of (relative_path, content).
fn collect_all_files(root: &Path) -> Vec<(String, String)> {
    let mut files = BTreeMap::new();
    collect_recursive(root, root, &mut files);
    files.into_iter().collect()
}

fn collect_recursive(root: &Path, dir: &Path, files: &mut BTreeMap<String, String>) {
    let mut entries: Vec<_> = std::fs::read_dir(dir)
        .unwrap()
        .filter_map(|e| e.ok())
        .collect();
    entries.sort_by_key(|e| e.file_name());

    for entry in entries {
        let path = entry.path();
        if path.is_dir() {
            collect_recursive(root, &path, files);
        } else {
            let rel = normalize_path(&path.strip_prefix(root).unwrap().to_string_lossy());
            let content = read_file_or_binary(&path);
            files.insert(rel, content);
        }
    }
}

/// Read a file as UTF-8 text, or return `[binary]` if the content is not valid UTF-8.
/// Panics on other I/O errors (e.g. permission denied, file not found).
fn read_file_or_binary(path: &Path) -> String {
    match std::fs::read_to_string(path) {
        Ok(content) => content.replace("\r\n", "\n"),
        Err(e) if e.kind() == std::io::ErrorKind::InvalidData => "[binary]".to_string(),
        Err(e) => panic!("failed to read {}: {e}", path.display()),
    }
}

impl TestProjectBuilder {
    /// Add a file with given contents (path relative to project root).
    pub fn file(mut self, path: &str, content: &str) -> Self {
        self.files.insert(path.to_string(), content.to_string());
        self
    }

    /// Run `ghat init` before overlaying files.
    pub fn init(mut self) -> Self {
        self.init = true;
        self
    }

    /// Build the project: create temp dir, optionally run init, write files.
    pub fn build(self) -> TestProject {
        let dir = tempfile::tempdir().expect("failed to create temp dir");

        if self.init {
            let output = Command::new(env!("CARGO_BIN_EXE_ghat"))
                .arg("init")
                .current_dir(dir.path())
                .output()
                .expect("failed to run ghat init");
            assert!(
                output.status.success(),
                "ghat init failed: {}",
                String::from_utf8_lossy(&output.stderr)
            );
        }

        for (path, content) in &self.files {
            let full_path = dir.path().join(path);
            if let Some(parent) = full_path.parent() {
                std::fs::create_dir_all(parent).unwrap();
            }
            std::fs::write(&full_path, content).unwrap();
        }

        TestProject { dir }
    }
}

/// Runs the ghat binary with given args and environment.
pub struct CommandRunner {
    project_dir: PathBuf,
    args: Vec<String>,
    envs: HashMap<String, String>,
}

/// Output from running a command.
pub struct CommandOutput {
    pub exit_code: i32,
    pub stdout: String,
    pub stderr: String,
}

impl fmt::Display for CommandOutput {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        writeln!(f, "exit_code: {}", self.exit_code)?;
        if !self.stderr.is_empty() {
            write!(f, "---stderr---\n{}", self.stderr)?;
            if !self.stderr.ends_with('\n') {
                writeln!(f)?;
            }
        }
        if !self.stdout.is_empty() {
            write!(f, "---stdout---\n{}", self.stdout)?;
            if !self.stdout.ends_with('\n') {
                writeln!(f)?;
            }
        }
        Ok(())
    }
}

impl CommandRunner {
    /// Set an environment variable for the command.
    pub fn env(mut self, key: &str, value: &str) -> Self {
        self.envs.insert(key.to_string(), value.to_string());
        self
    }

    /// Run the command and return structured output.
    pub fn run(self) -> CommandOutput {
        let mut cmd = Command::new(env!("CARGO_BIN_EXE_ghat"));
        for arg in &self.args {
            cmd.arg(arg);
        }
        cmd.current_dir(&self.project_dir);
        for (k, v) in &self.envs {
            cmd.env(k, v);
        }

        let output = cmd.output().expect("failed to run ghat");

        // Collect all path representations that might appear in the output.
        // Tools like tsgo or canonicalize() can resolve symlinks or short names,
        // producing paths that differ from what tempdir() returns.
        // Only forward-slash forms are needed since sanitize_output normalizes
        // all backslashes before doing replacements.
        let mut dir_variants: Vec<String> = Vec::new();
        if let Ok(canonical) = self.project_dir.canonicalize() {
            let s = canonical.to_string_lossy().to_string();
            // On Windows, canonicalize adds a \\?\ prefix - strip it.
            let s = s.strip_prefix(r"\\?\").unwrap_or(&s).to_string();
            dir_variants.push(s.replace('\\', "/"));
        }
        let s = self.project_dir.to_string_lossy().replace('\\', "/");
        dir_variants.push(s);
        dir_variants.dedup();

        let stdout = sanitize_output(&output.stdout, &dir_variants);
        let stderr = sanitize_output(&output.stderr, &dir_variants);

        CommandOutput {
            exit_code: output.status.code().unwrap_or(-1),
            stdout,
            stderr,
        }
    }
}

/// Normalize a relative path to always use forward slashes.
fn normalize_path(p: &str) -> String {
    p.replace('\\', "/")
}

/// Replace temp directory paths and unstable timing values in command output.
fn sanitize_output(raw: &[u8], dir_variants: &[String]) -> String {
    let mut s = String::from_utf8_lossy(raw).into_owned();
    // Normalize all backslashes to forward slashes before doing replacements.
    // On Windows, the binary outputs paths with backslashes (e.g. `.github/workflows\ci.yaml`).
    s = s.replace('\\', "/");
    // Replace all known path variants (longest first to avoid partial matches).
    for variant in dir_variants {
        s = s.replace(variant.as_str(), "[ROOT]");
    }
    // Redact durations like "in 42.02ms", "in 1.23s", "in 350.00µs"
    let mut result = String::with_capacity(s.len());
    let mut rest = s.as_str();
    while let Some(pos) = rest.find(" in ") {
        let after = &rest[pos + 4..];
        // Check if this looks like a duration: digits, optional dot+digits, then a time unit
        if let Some(end) = parse_duration_suffix(after) {
            result.push_str(&rest[..pos]);
            result.push_str(" in [TIME]");
            rest = &after[end..];
        } else {
            result.push_str(&rest[..pos + 4]);
            rest = after;
        }
    }
    result.push_str(rest);
    result
}

/// If `s` starts with a duration like `42.02ms`, return the byte length consumed.
fn parse_duration_suffix(s: &str) -> Option<usize> {
    let bytes = s.as_bytes();
    let mut i = 0;
    // Consume digits
    if i >= bytes.len() || !bytes[i].is_ascii_digit() {
        return None;
    }
    while i < bytes.len() && bytes[i].is_ascii_digit() {
        i += 1;
    }
    // Optional fractional part
    if i < bytes.len() && bytes[i] == b'.' {
        i += 1;
        while i < bytes.len() && bytes[i].is_ascii_digit() {
            i += 1;
        }
    }
    // Time unit
    let rest = &s[i..];
    for unit in &["ms", "µs", "ns", "s"] {
        if rest.starts_with(unit) {
            return Some(i + unit.len());
        }
    }
    None
}
