name: CI
on:
  push:
    branches:
    - main
  pull_request: {}
permissions:
  contents: read
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
        - runner: ubuntu-24.04
          toolchain: stable
        - runner: ubuntu-24.04-arm
          toolchain: stable
        - runner: macos-26
          toolchain: stable
        - runner: windows-2025
          toolchain: stable-x86_64-pc-windows-gnu
      fail-fast: false
    steps:
    - id: step_0
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - id: step_1
      uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5
    - id: step_2
      uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9
      with:
        toolchain: ${{ matrix.toolchain }}
    - id: step_3
      run: cargo test
