name: CI
on:
  push:
    branches:
    - main
  pull_request: {}
permissions:
  contents: read
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - id: __step_0
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - id: __step_1
      uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5
    - id: __step_2
      uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9
      with:
        toolchain: stable
    - id: __step_3
      run: cargo test
